name: 'CI'

on:
  push:
    branches:
      - 'development'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lisp:
          - sbcl

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v2

      - name: setup cache folders
        run: |
          sudo mkdir -p /usr/local/etc/roswell
          sudo chown "${USER}" /usr/local/etc/roswell
          # Here the ros binary will be restored:
          sudo chown "${USER}" /usr/local/bin

      - name: current date for quicklisp
        id: current-month
        run: |
          echo "CURRENT_MONTH=$(date -u "+%Y-%m")" >> $GITHUB_OUTPUT

      - name: Cache Roswell Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-roswell
        with:
          path: |
            /usr/local/bin/ros
            /usr/local/etc/roswell
            ~/.cache/common-lisp/
            ~/.roswell
            .qlot
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('qlfile.lock') }}"

      - name: Restore Path To Cached Files
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
          echo .qlot/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'

      - uses: 40ants/setup-lisp@v2
        if: steps.cache.outputs.cache-hit != 'true'

      - name: run
        run: |
          ros use sbcl
          LISP=sbcl-bin make tests
